name: gum
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7.9
  - cpuonly=1.0=0
  - cython
  - pip
  - pip:
    - gdown
    - nltk
    - torch
    - transformers
    - udapi
    - urllib3
    - sentencepiece

