python check_model.py
:: Run allennlp to predict on eng.pdtb.missing_test.rels which is generated by the GDTB main.py build script for relations that have no discodisco probabilities
allennlp predict models\eng.pdtb.pdtb_flair_clone\model.tar.gz eng.pdtb.missing_test.rels --silent --use-dataset-reader --output-file out_test.json
:: Create the necessary files in data\discodisco_preds\
python generate_rels_from_json.py